(** 2019-01-30 **)
ACTION Act_InitLocal:
	
	//Input Reference Link To Local Variable
	p_bPrep ACCESS ADR(bPrep);
	p_bEn ACCESS ADR(bEn);
	p_bDis ACCESS ADR(bDis);
	p_eNtParamMag ACCESS ADR(eNtParamMag);
	p_usiMcParamProdSelMcMod ACCESS ADR(usiMcParamProdSelMcMod);
	p_bOpsStatusRun ACCESS ADR(bOpsStatusRun);
	p_bBufferMagPresent1 ACCESS ADR(bBufferMagPresent1);
	p_bBufferMagPresent2 ACCESS ADR(bBufferMagPresent2);
	p_bBufferMagPresent3 ACCESS ADR(bBufferMagPresent3);
	p_tyBufferStat1 ACCESS ADR(tyBufferStat1);
	p_tyBufferStat2 ACCESS ADR(tyBufferStat2);
	p_tyBufferStat3 ACCESS ADR(tyBufferStat3);
	
END_ACTION
