#ifndef __AS__TYPE_
#define __AS__TYPE_
typedef struct {
	unsigned char bit0  : 1;
	unsigned char bit1  : 1;
	unsigned char bit2  : 1;
	unsigned char bit3  : 1;
	unsigned char bit4  : 1;
	unsigned char bit5  : 1;
	unsigned char bit6  : 1;
	unsigned char bit7  : 1;
} _1byte_bit_field_;

typedef struct {
	unsigned short bit0  : 1;
	unsigned short bit1  : 1;
	unsigned short bit2  : 1;
	unsigned short bit3  : 1;
	unsigned short bit4  : 1;
	unsigned short bit5  : 1;
	unsigned short bit6  : 1;
	unsigned short bit7  : 1;
	unsigned short bit8  : 1;
	unsigned short bit9  : 1;
	unsigned short bit10 : 1;
	unsigned short bit11 : 1;
	unsigned short bit12 : 1;
	unsigned short bit13 : 1;
	unsigned short bit14 : 1;
	unsigned short bit15 : 1;
} _2byte_bit_field_;

typedef struct {
	unsigned long bit0  : 1;
	unsigned long bit1  : 1;
	unsigned long bit2  : 1;
	unsigned long bit3  : 1;
	unsigned long bit4  : 1;
	unsigned long bit5  : 1;
	unsigned long bit6  : 1;
	unsigned long bit7  : 1;
	unsigned long bit8  : 1;
	unsigned long bit9  : 1;
	unsigned long bit10 : 1;
	unsigned long bit11 : 1;
	unsigned long bit12 : 1;
	unsigned long bit13 : 1;
	unsigned long bit14 : 1;
	unsigned long bit15 : 1;
	unsigned long bit16 : 1;
	unsigned long bit17 : 1;
	unsigned long bit18 : 1;
	unsigned long bit19 : 1;
	unsigned long bit20 : 1;
	unsigned long bit21 : 1;
	unsigned long bit22 : 1;
	unsigned long bit23 : 1;
	unsigned long bit24 : 1;
	unsigned long bit25 : 1;
	unsigned long bit26 : 1;
	unsigned long bit27 : 1;
	unsigned long bit28 : 1;
	unsigned long bit29 : 1;
	unsigned long bit30 : 1;
	unsigned long bit31 : 1;
} _4byte_bit_field_;
#endif

#ifndef __AS__TYPE_tyDigitalInput
#define __AS__TYPE_tyDigitalInput
typedef struct tyDigitalInput
{	plcbit bSafetyRlySig;
	plcbit bEStopSig;
	plcbit bCoverSWSig;
	plcbit bUBAA;
	plcbit bUBAB;
	plcbit bUBAAStat;
	plcbit bUBABStat;
	plcbit bPusherExtRS;
	plcbit bPusherRetRS;
	plcbit bConvLftSen;
	plcbit bConvMidSen;
	plcbit bConvRgtSen;
	plcbit bConvClrSen;
	plcbit bOvenInfeedSigA;
	plcbit bOvenInfeedSigB;
	plcbit bLifterTimingBeltSen;
	plcbit bLifterSafetyLmtSW1;
	plcbit bLifterSafetyLmtSW2;
	plcbit bMag1FixedClampRS;
	plcbit bMag1FixedUnclampRS;
	plcbit bMag1RemoteClampRS;
	plcbit bMag1RemoteUnclampRS;
	plcbit bMag2FixedClampRS;
	plcbit bMag2FixedUnclampRS;
	plcbit bMag2RemoteClampRS;
	plcbit bMag2RemoteUnclampRS;
	plcbit bMag3FixedClampRS;
	plcbit bMag3FixedUnclampRS;
	plcbit bMag3RemoteClampRS;
	plcbit bMag3RemoteUnclampRS;
	plcbit bInShutterOpenRS;
	plcbit bInShutterCloseRS;
	plcbit bOutShutterOpenRS;
	plcbit bOutShutterCloseRS;
	plcbit bMagPresentSen1;
	plcbit bMagPresentSen2;
	plcbit bMagPresentSen3;
	plcbit bMagConvEntSen1;
	plcbit bMagConvEntSen2;
	plcbit bMagConvEntSen3;
	plcbit bMag1AIVInPosSen1;
	plcbit bMag1AIVInPosSen2;
	plcbit bMag2AIVInPosSen1;
	plcbit bMag2AIVInPosSen2;
	plcbit bMag3AIVInPosSen1;
	plcbit bMag3AIVInPosSen2;
	plcbit bMag1OrientChkSen1;
	plcbit bMag1OrientChkSen2;
	plcbit bMag2OrientChkSen1;
	plcbit bMag2OrientChkSen2;
	plcbit bMag3OrientChkSen1;
	plcbit bMag3OrientChkSen2;
	plcbit bUSWidthChkSen;
	plcbit bConvLineAInletSen;
	plcbit bConvLineBInletSen;
	plcbit bMagConvHeightSen1;
	plcbit bMagConvHeightSen2;
	plcbit bMagConvHeightSen3;
	plcbit bMagConvSmallMagSen1;
	plcbit bMagConvSmallMagSen2;
	plcbit bMagConvSmallMagSen3;
	plcbit bMagConvLargeMagSen1;
	plcbit bMagConvLargeMagSen2;
	plcbit bMagConvLargeMagSen3;
	plcbit bMagConvCAB717MagSen1;
	plcbit bMagConvCAB717MagSen2;
	plcbit bMagConvCAB717MagSen3;
	plcbit bMag1SelUnClampRS;
	plcbit bMag2SelUnClampRS;
	plcbit bMag3SelUnClampRS;
	plcbit bMag1WallEngageRS;
	plcbit bMag1WallDisengageRS;
	plcbit bMag2WallEngageRS;
	plcbit bMag2WallDisengageRS;
	plcbit bMag3WallEngageRS;
	plcbit bMag3WallDisengageRS;
	plcbit bMag1SafetyBarExtRS;
	plcbit bMag1SafetyBarRetRS;
	plcbit bMag2SafetyBarExtRS;
	plcbit bMag2SafetyBarRetRS;
	plcbit bMag3SafetyBarExtRS;
	plcbit bMag3SafetyBarRetRS;
	plcbit bSOT1Receive;
	plcbit bSOT1AIVError;
	plcbit bSOT1AIVSizeLarge;
	plcbit bSOT1AIVReady;
	plcbit bSOT1AIVAvailable;
	plcbit bSOT2Receive;
	plcbit bSOT2AIVError;
	plcbit bSOT2AIVSizeLarge;
	plcbit bSOT2AIVReady;
	plcbit bSOT2AIVAvailable;
	plcbit bSOT3Receive;
	plcbit bSOT3AIVError;
	plcbit bSOT3AIVSizeLarge;
	plcbit bSOT3AIVReady;
	plcbit bSOT3AIVAvailable;
	plcbit bSOT4Receive;
	plcbit bSOT4AIVError;
	plcbit bSOT4AIVSizeLarge;
	plcbit bSOT4AIVReady;
	plcbit bSOT4AIVAvailable;
	plcbit bFleetManagerReady;
	plcbit bPusherExtSlwSen;
	plcbit bPusherRetSlwSen;
	plcbit bMtrPshrTorqueSig;
	plcbit bMtrPshrAlmSig;
	plcbit bMagWidthChkSen;
	plcbit bPshrAntiJam;
	plcbit bInMagConvEntSen;
	plcbit bInMagConvExtSen;
	plcbit bInMagConvMidSen;
	plcbit bOutMagConvEntSen;
	plcbit bOutMagConvExtSen;
	plcbit bOutMagConvMidSen;
	plcbit bInMagConv2EntSen;
	plcbit bInMagConv2ExtSen;
	plcbit bInMagConv2MidSen;
	plcbit bOutMagConv2EntSen;
	plcbit bOutMagConv2ExtSen;
	plcbit bOutMagConv2MidSen;
	plcbit bLifterLmtSW;
	plcbit bLifter2LmtSW;
	plcbit bMtrOverloadSig;
	plcbit bOutShutterOpenRS2;
	plcbit bOutShutterCloseRS2;
	plcbit bOutShutterOpenRS3;
	plcbit bOutShutterCloseRS3;
	plcbit bMag1FixedClampSen;
	plcbit bMag2FixedClampSen;
	plcbit bMag3FixedClampSen;
	plcbit bCurtainSenPB;
	plcbit bCurtainSen;
	plcbit bCurtainSafetySig;
	plcbit bHighMagDetSen1;
	plcbit bHighMagDetSen2;
	plcbit bHighMagDetSen3;
	plcbit bInletStopperASen;
	plcbit diScanComplSig;
	plcbit diPCBScanSen;
	plcbit bSPARE17;
	plcbit bSPARE18;
	plcbit bSPARE19;
	plcbit bSPARE20;
} tyDigitalInput;
#endif

#ifndef __AS__TYPE_eFBStatus
#define __AS__TYPE_eFBStatus
typedef enum eFBStatus
{	Idle = 0,
	Done = 1,
	Busy = 2,
	Error = 3,
} eFBStatus;
#endif

#ifndef __AS__TYPE_eAlmSeverity
#define __AS__TYPE_eAlmSeverity
typedef enum eAlmSeverity
{	AlmSeverityNA = 0,
	AlmSeverityError = 1,
	AlmSeverityWarning = 2,
	AlmSeverityInfo = 3,
} eAlmSeverity;
#endif

#ifndef __AS__TYPE_tyAlmDat
#define __AS__TYPE_tyAlmDat
typedef struct tyAlmDat
{	unsigned long udiCode;
	eAlmSeverity eSeverity;
	plcstring sProgNm[16];
	plcstring sAlmMsg[201];
	plcstring sRcyMsg[201];
	unsigned long udiRunTime;
	unsigned long udiModuleNum;
	plcbit bAlm;
	plcbit bWarning;
} tyAlmDat;
#endif

_BUR_LOCAL eFBStatus eStatus4;
_BUR_LOCAL tyAlmDat tyAlmData1;
_BUR_LOCAL tyAlmDat tyAlmData2;
_BUR_LOCAL tyAlmDat tyAlmData3;
_BUR_LOCAL tyAlmDat tyAlmData4;
_BUR_LOCAL tyAlmDat tyAlmData5;
_BUR_LOCAL tyAlmDat tyAlmData6;
_BUR_LOCAL tyDigitalInput tyDInput;
_GLOBAL unsigned long p_DIAlmData1;
_GLOBAL unsigned long p_DIAlmData2;
_GLOBAL unsigned long p_DIAlmData3;
_GLOBAL unsigned long p_DIAlmData4;
_GLOBAL unsigned long p_DIAlmData5;
_GLOBAL unsigned long p_DIAlmData6;
_GLOBAL unsigned long p_DI;
_GLOBAL unsigned long p_DISafetyRlySig;
_GLOBAL unsigned long p_DIEStopSig;
_GLOBAL unsigned long p_DICoverSWSig;
_GLOBAL unsigned long p_DIUBAA;
_GLOBAL unsigned long p_DIUBAB;
_GLOBAL unsigned long p_DIUBAAStat;
_GLOBAL unsigned long p_DIUBABStat;
_GLOBAL unsigned long p_DIPusherExtRS;
_GLOBAL unsigned long p_DIPusherRetRS;
_GLOBAL unsigned long p_DIConvLftSen;
_GLOBAL unsigned long p_DIConvMidSen;
_GLOBAL unsigned long p_DIConvRgtSen;
_GLOBAL unsigned long p_DIConvClrSen;
_GLOBAL unsigned long p_DIOvenInfeedSigA;
_GLOBAL unsigned long p_DIOvenInfeedSigB;
_GLOBAL unsigned long p_DILifterTimingBeltSen;
_GLOBAL unsigned long p_DILifterSafetyLmtSW1;
_GLOBAL unsigned long p_DILifterSafetyLmtSW2;
_GLOBAL unsigned long p_DIMag1FixedClampRS;
_GLOBAL unsigned long p_DIMag1FixedUnclampRS;
_GLOBAL unsigned long p_DIMag1RemoteClampRS;
_GLOBAL unsigned long p_DIMag1RemoteUnclampRS;
_GLOBAL unsigned long p_DIMag2FixedClampRS;
_GLOBAL unsigned long p_DIMag2FixedUnclampRS;
_GLOBAL unsigned long p_DIMag2RemoteClampRS;
_GLOBAL unsigned long p_DIMag2RemoteUnclampRS;
_GLOBAL unsigned long p_DIMag3FixedClampRS;
_GLOBAL unsigned long p_DIMag3FixedUnclampRS;
_GLOBAL unsigned long p_DIMag3RemoteClampRS;
_GLOBAL unsigned long p_DIMag3RemoteUnclampRS;
_GLOBAL unsigned long p_DIInShutterOpenRS;
_GLOBAL unsigned long p_DIInShutterCloseRS;
_GLOBAL unsigned long p_DIOutShutterOpenRS;
_GLOBAL unsigned long p_DIOutShutterCloseRS;
_GLOBAL unsigned long p_DIOutShutterOpenRS2;
_GLOBAL unsigned long p_DIOutShutterCloseRS2;
_GLOBAL unsigned long p_DIOutShutterOpenRS3;
_GLOBAL unsigned long p_DIOutShutterCloseRS3;
_GLOBAL unsigned long p_DIMagPresentSen1;
_GLOBAL unsigned long p_DIMagPresentSen2;
_GLOBAL unsigned long p_DIMagPresentSen3;
_GLOBAL unsigned long p_DIMagConvEntSen1;
_GLOBAL unsigned long p_DIMagConvEntSen2;
_GLOBAL unsigned long p_DIMagConvEntSen3;
_GLOBAL unsigned long p_DIMag1AIVInPosSen1;
_GLOBAL unsigned long p_DIMag1AIVInPosSen2;
_GLOBAL unsigned long p_DIMag2AIVInPosSen1;
_GLOBAL unsigned long p_DIMag2AIVInPosSen2;
_GLOBAL unsigned long p_DIMag3AIVInPosSen1;
_GLOBAL unsigned long p_DIMag3AIVInPosSen2;
_GLOBAL unsigned long p_DIMag1OrientChkSen1;
_GLOBAL unsigned long p_DIMag1OrientChkSen2;
_GLOBAL unsigned long p_DIMag2OrientChkSen1;
_GLOBAL unsigned long p_DIMag2OrientChkSen2;
_GLOBAL unsigned long p_DIMag3OrientChkSen1;
_GLOBAL unsigned long p_DIMag3OrientChkSen2;
_GLOBAL unsigned long p_DIUSWidthChkSen;
_GLOBAL unsigned long p_DIConvLineAInletSen;
_GLOBAL unsigned long p_DIConvLineBInletSen;
_GLOBAL unsigned long p_DIMagConvHeightSen1;
_GLOBAL unsigned long p_DIMagConvHeightSen2;
_GLOBAL unsigned long p_DIMagConvHeightSen3;
_GLOBAL unsigned long p_DIMagConvSmallMagSen1;
_GLOBAL unsigned long p_DIMagConvSmallMagSen2;
_GLOBAL unsigned long p_DIMagConvSmallMagSen3;
_GLOBAL unsigned long p_DIMagConvLargeMagSen1;
_GLOBAL unsigned long p_DIMagConvLargeMagSen2;
_GLOBAL unsigned long p_DIMagConvLargeMagSen3;
_GLOBAL unsigned long p_DIMagConvCAB717MagSen1;
_GLOBAL unsigned long p_DIMagConvCAB717MagSen2;
_GLOBAL unsigned long p_DIMagConvCAB717MagSen3;
_GLOBAL unsigned long p_DIMag1SelUnclampRS;
_GLOBAL unsigned long p_DIMag2SelUnclampRS;
_GLOBAL unsigned long p_DIMag3SelUnclampRS;
_GLOBAL unsigned long p_DIMag1SafetyBarExtRS;
_GLOBAL unsigned long p_DIMag1SafetyBarRetRS;
_GLOBAL unsigned long p_DIMag2SafetyBarExtRS;
_GLOBAL unsigned long p_DIMag2SafetyBarRetRS;
_GLOBAL unsigned long p_DIMag3SafetyBarExtRS;
_GLOBAL unsigned long p_DIMag3SafetyBarRetRS;
_GLOBAL unsigned long p_DIMag1WallEngageRS;
_GLOBAL unsigned long p_DIMag1WallDisengageRS;
_GLOBAL unsigned long p_DIMag2WallEngageRS;
_GLOBAL unsigned long p_DIMag2WallDisengageRS;
_GLOBAL unsigned long p_DIMag3WallEngageRS;
_GLOBAL unsigned long p_DIMag3WallDisengageRS;
_GLOBAL unsigned long p_DISOT1Receive;
_GLOBAL unsigned long p_DISOT1Error;
_GLOBAL unsigned long p_DISOT1SizeLarge;
_GLOBAL unsigned long p_DISOT1Ready;
_GLOBAL unsigned long p_DISOT1Available;
_GLOBAL unsigned long p_DISOT2Receive;
_GLOBAL unsigned long p_DISOT2Error;
_GLOBAL unsigned long p_DISOT2SizeLarge;
_GLOBAL unsigned long p_DISOT2Ready;
_GLOBAL unsigned long p_DISOT2Available;
_GLOBAL unsigned long p_DISOT3Receive;
_GLOBAL unsigned long p_DISOT3Error;
_GLOBAL unsigned long p_DISOT3SizeLarge;
_GLOBAL unsigned long p_DISOT3Ready;
_GLOBAL unsigned long p_DISOT3Available;
_GLOBAL unsigned long p_DIFleetManagerActive;
_GLOBAL unsigned long p_DIPusherExtSlwSen;
_GLOBAL unsigned long p_DIPusherRetSlwSen;
_GLOBAL unsigned long p_DIMtrPshrTorqueSig;
_GLOBAL unsigned long p_DIMtrPshrAlmSig;
_GLOBAL unsigned long p_DIMagWidthChkSen;
_GLOBAL unsigned long p_DIPshrAntiJamSen;
_GLOBAL unsigned long p_DIInMagConvEntSen;
_GLOBAL unsigned long p_DIInMagConvExtSen;
_GLOBAL unsigned long p_DIInMagConvMidSen;
_GLOBAL unsigned long p_DIOutMagConvEntSen;
_GLOBAL unsigned long p_DIOutMagConvExtSen;
_GLOBAL unsigned long p_DIOutMagConvMidSen;
_GLOBAL unsigned long p_DIInMagConv2EntSen;
_GLOBAL unsigned long p_DIInMagConv2ExtSen;
_GLOBAL unsigned long p_DIInMagConv2MidSen;
_GLOBAL unsigned long p_DIOutMagConv2EntSen;
_GLOBAL unsigned long p_DIOutMagConv2ExtSen;
_GLOBAL unsigned long p_DIOutMagConv2MidSen;
_GLOBAL unsigned long p_DILifterLmtSW;
_GLOBAL unsigned long p_DILifter2LmtSW;
_GLOBAL unsigned long p_DIMtrOverloadSig;
_GLOBAL unsigned long p_DIMag1FixedClampSen;
_GLOBAL unsigned long p_DIMag2FixedClampSen;
_GLOBAL unsigned long p_DIMag3FixedClampSen;
_GLOBAL unsigned long p_DICurtainSenPB;
_GLOBAL unsigned long p_DICurtainSen;
_GLOBAL unsigned long p_DIHighMagDetSen1;
_GLOBAL unsigned long p_DIHighMagDetSen2;
_GLOBAL unsigned long p_DIHighMagDetSen3;
_GLOBAL unsigned long p_DIInletStopperASen;
_GLOBAL unsigned long p_DIPCBScanComplSig;
_GLOBAL unsigned long p_DILifterSafetyStatus;
