
ACTION Act_EntP0900Disp: 
	
	//Access Address
	p_tyC0005Main ACCESS ADR(tyCommon.tyMain);
	
	p_tyC0007Notif ACCESS ADR(tyCommon.tyNotif);
	
	p_tyC0008MsgBox ACCESS ADR(tyP0900GenIn.tyMsgBoxHide);
	
	p_tyC0009Info ACCESS ADR(tyCommon.tyInfo);
	
	p_tyP0900GenIn1 ACCESS ADR(tyP0900GenIn.tyGenIn1);
	p_tyP0900GenIn2 ACCESS ADR(tyP0900GenIn.tyGenIn2);
	p_tyP0900GenIn3 ACCESS ADR(tyP0900GenIn.tyGenIn3);
	
END_ACTION
