(** 2019-03-25 **)
ACTION Act_InitLocal:
	
	//Input Reference Link To Local Variable
	p_eAct ACCESS ADR(eAct);
	
//	p_bSvyUpdateUIData ACCESS p_SvyHermesUpdateUIData;//new for Hermes 1.3
//	p_sWorkOrderId ACCESS p_SvyHermesWorkOrderId;
//	p_tySendWorkOrderData ACCESS p_SvyHermesSendWorkOrderData
//	p_tySvyHermesSendWorkOrderData ACCESS p_SvyHermesSendWorkOrderData;
//	p_tySvyHermesBypassSendWOData ACCESS p_SvyHermesBypassSendWOData;
//	p_diReqLoaderWidthInUM ACCESS p_ReqLoaderWidthInUM;
//	p_bQueryBypassWorkOrder ACCESS p_QueryBypassWorkOrder;
//	p_bReplyBypassWorkOrderInfo ACCESS p_ReplyBypassWorkOrderInfo;
	//	
//	p_bTCPSvrUBA ACCESS ADR(bTCPSvrUBA);
//	p_bTCPSvrUBA2 ACCESS ADR(bTCPSvrUBA2);
//	p_bTCPSvrDSB ACCESS ADR(bTCPSvrDSB);
//	p_bTCPSvrDSB2 ACCESS ADR(bTCPSvrDSB);
	
END_ACTION
